services:
  - type: web
    name: telegram-bot-lentera4d
    runtime: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8074357218:AAGhj89beSOtsLTe8ikVhvC2bAjOlxqNEWE
